# -*- coding: utf-8 -*-
# Translatable strings that pylupdate5 cannot extract automatically.
# Calling QCoreApplication.translate() directly with literal strings
# so pylupdate5 picks them up when generating/updating .ts files.
from qgis.PyQt.QtCore import QCoreApplication

# Common fields
QCoreApplication.translate('FieldPrettyNames', "Identifier")
QCoreApplication.translate('FieldPrettyNames', "Tag")
QCoreApplication.translate('FieldPrettyNames', "Description")
QCoreApplication.translate('FieldPrettyNames', "Age")
QCoreApplication.translate('FieldPrettyNames', "Installation Date")
QCoreApplication.translate('FieldPrettyNames', "Initial Status")
QCoreApplication.translate('FieldPrettyNames', "Type")
QCoreApplication.translate('FieldPrettyNames', "Status")
QCoreApplication.translate('FieldPrettyNames', "IsActive")

# Pipes
QCoreApplication.translate('FieldPrettyNames', "Length")
QCoreApplication.translate('FieldPrettyNames', "Diameter")
QCoreApplication.translate('FieldPrettyNames', "Roughness Coeff")
QCoreApplication.translate('FieldPrettyNames', "Loss Coefficient")
QCoreApplication.translate('FieldPrettyNames', "Material")
QCoreApplication.translate('FieldPrettyNames', "Leak Area")
QCoreApplication.translate('FieldPrettyNames', "Leak Expansion Rate")
QCoreApplication.translate('FieldPrettyNames', "Bulk Coefficient")
QCoreApplication.translate('FieldPrettyNames', "Wall Coefficient")

# Junctions
QCoreApplication.translate('FieldPrettyNames', "Elevation")
QCoreApplication.translate('FieldPrettyNames', "Base Demand")
QCoreApplication.translate('FieldPrettyNames', "Pattern Demand")
QCoreApplication.translate('FieldPrettyNames', "Demand Pattern")
QCoreApplication.translate('FieldPrettyNames', "Emitter Coefficient")
QCoreApplication.translate('FieldPrettyNames', "Initial Quality")

# Multiple Demands
QCoreApplication.translate('FieldPrettyNames', "Base Demand")

# Tanks
QCoreApplication.translate('FieldPrettyNames', "Initial Level")
QCoreApplication.translate('FieldPrettyNames', "Minimum Level")
QCoreApplication.translate('FieldPrettyNames', "Maximum Level")
QCoreApplication.translate('FieldPrettyNames', "Volume")
QCoreApplication.translate('FieldPrettyNames', "Minimum Volume")
QCoreApplication.translate('FieldPrettyNames', "Volume Curve")
QCoreApplication.translate('TimeSeriesGlobals', "Total Water Supply")
QCoreApplication.translate('TimeSeriesGlobals', "Total Water Demand")
QCoreApplication.translate('TimeSeriesGlobals', "Total Stored Volume")
QCoreApplication.translate('TimeSeriesGlobals', "Total Tank Spill Flow")
QCoreApplication.translate('TimeSeriesGlobals', "Average Node Pressure")
QCoreApplication.translate('TimeSeriesGlobals', "System")
QCoreApplication.translate('TimeSeriesGlobals', "Supply")
QCoreApplication.translate('TimeSeriesGlobals', "Demand")
QCoreApplication.translate('TimeSeriesGlobals', "Storage")
QCoreApplication.translate('TimeSeriesGlobals', "Spill")
QCoreApplication.translate('TimeSeriesGlobals', "Pressure")
QCoreApplication.translate('FieldPrettyNames', "Overflow Condition")
QCoreApplication.translate('FieldPrettyNames', "Mixing Model")
QCoreApplication.translate('FieldPrettyNames', "Mixing Fraction")

# Reservoirs
QCoreApplication.translate('FieldPrettyNames', "Total Head")
QCoreApplication.translate('FieldPrettyNames', "Head Pattern")

# Valves
QCoreApplication.translate('FieldPrettyNames', "Setting")
QCoreApplication.translate('FieldPrettyNames', "HeadLoss Curve")
QCoreApplication.translate('FieldPrettyNames', "Valve Type")

# Pumps
QCoreApplication.translate('FieldPrettyNames', "Head Curve")
QCoreApplication.translate('FieldPrettyNames', "Pump Curve")
QCoreApplication.translate('FieldPrettyNames', "Power")
QCoreApplication.translate('FieldPrettyNames', "Speed")
QCoreApplication.translate('FieldPrettyNames', "Speed Pattern")
QCoreApplication.translate('FieldPrettyNames', "Efficiency Curve")
QCoreApplication.translate('FieldPrettyNames', "Energy Price")
QCoreApplication.translate('FieldPrettyNames', "Price Pattern")

# Curves
QCoreApplication.translate('FieldPrettyNames', "Value X axis")
QCoreApplication.translate('FieldPrettyNames', "Value Y axis")
QCoreApplication.translate('FieldPrettyNames', "Curve Type")

# Patterns
QCoreApplication.translate('FieldPrettyNames', "Time Order")
QCoreApplication.translate('FieldPrettyNames', "Multiplier")
QCoreApplication.translate('FieldPrettyNames', "Pattern Type")

# Materials
QCoreApplication.translate('FieldPrettyNames', "ShortName")
QCoreApplication.translate('FieldPrettyNames', "Initial Roughness")
QCoreApplication.translate('FieldPrettyNames', "Annual Increment")

# Sources
QCoreApplication.translate('FieldPrettyNames', "Source Quality")
QCoreApplication.translate('FieldPrettyNames', "Source Pattern")
QCoreApplication.translate('FieldPrettyNames', "Quality Pattern")
QCoreApplication.translate('FieldPrettyNames', "Source Type")

# Meters
QCoreApplication.translate('FieldPrettyNames', "Meter Type")

# Service Connections
QCoreApplication.translate('FieldPrettyNames', "Reliability")

# Isolation Valves
QCoreApplication.translate('FieldPrettyNames', "Available")

# Options
QCoreApplication.translate('FieldPrettyNames', "Specific Gravity")
QCoreApplication.translate('FieldPrettyNames', "Viscosity")
QCoreApplication.translate('FieldPrettyNames', "Demand Multiplier")
QCoreApplication.translate('FieldPrettyNames', "Emitter Exponent")
QCoreApplication.translate('FieldPrettyNames', "Minimum Pressure")
QCoreApplication.translate('FieldPrettyNames', "Required Pressure")
QCoreApplication.translate('FieldPrettyNames', "Pressure Exponent")
QCoreApplication.translate('FieldPrettyNames', "Diffusivity")
QCoreApplication.translate('FieldPrettyNames', "Global Bulk")
QCoreApplication.translate('FieldPrettyNames', "Global Wall")
QCoreApplication.translate('FieldPrettyNames', "Limiting Potential")
QCoreApplication.translate('FieldPrettyNames', "Global Efficiency")
QCoreApplication.translate('FieldPrettyNames', "Global Price")
QCoreApplication.translate('FieldPrettyNames', "Demand Charge")

# Result nodes
QCoreApplication.translate('FieldPrettyNames', "Pressure")
QCoreApplication.translate('FieldPrettyNames', "Head")
QCoreApplication.translate('FieldPrettyNames', "Demand")
QCoreApplication.translate('FieldPrettyNames', "Full demand")
QCoreApplication.translate('FieldPrettyNames', "Demand Deficit")
QCoreApplication.translate('FieldPrettyNames', "Leakage Flow")
QCoreApplication.translate('FieldPrettyNames', "Emitter Flow")
QCoreApplication.translate('FieldPrettyNames', "Tank Volume")

# Result links
QCoreApplication.translate('FieldPrettyNames', "Flow")
QCoreApplication.translate('FieldPrettyNames', "Velocity")
QCoreApplication.translate('FieldPrettyNames', "HeadLoss")
QCoreApplication.translate('FieldPrettyNames', "Unit HeadLoss")
QCoreApplication.translate('FieldPrettyNames', "Friction factor")
QCoreApplication.translate('FieldPrettyNames', "Energy")
QCoreApplication.translate('FieldPrettyNames', "Reaction Rate")

# Result nodes and links
QCoreApplication.translate('FieldPrettyNames', "Element Type")
QCoreApplication.translate('FieldPrettyNames', "Node Type")
QCoreApplication.translate('FieldPrettyNames', "Link Type")
QCoreApplication.translate('FieldPrettyNames', "Simulation Time")

# Quality results (dynamic — also translated via getQualityDisplayName)
QCoreApplication.translate('FieldPrettyNames', "Chemical")
QCoreApplication.translate('FieldPrettyNames', "Trace")

# Plural display names — values of PLURAL_PROPERTY_NAMES in qgisred_field_utils.py.
# getPluralProperty() translates them in the 'FieldPrettyNames' context, but they
# live in a dict so pylupdate cannot see them there. Keep both lists in sync.
QCoreApplication.translate('FieldPrettyNames', "Ages")
QCoreApplication.translate('FieldPrettyNames', "Base Demands")
QCoreApplication.translate('FieldPrettyNames', "Bulk Coefficients")
QCoreApplication.translate('FieldPrettyNames', "Curve Types")
QCoreApplication.translate('FieldPrettyNames', "Demand Charges")
QCoreApplication.translate('FieldPrettyNames', "Demand Deficits")
QCoreApplication.translate('FieldPrettyNames', "Demand Multipliers")
QCoreApplication.translate('FieldPrettyNames', "Demand Patterns")
QCoreApplication.translate('FieldPrettyNames', "Demands")
QCoreApplication.translate('FieldPrettyNames', "Descriptions")
QCoreApplication.translate('FieldPrettyNames', "Diameters")
QCoreApplication.translate('FieldPrettyNames', "Efficiency Curves")
QCoreApplication.translate('FieldPrettyNames', "Element Types")
QCoreApplication.translate('FieldPrettyNames', "Elevations")
QCoreApplication.translate('FieldPrettyNames', "Emitter Coefficients")
QCoreApplication.translate('FieldPrettyNames', "Emitter Exponents")
QCoreApplication.translate('FieldPrettyNames', "Emitter Flows")
QCoreApplication.translate('FieldPrettyNames', "Energy Prices")
QCoreApplication.translate('FieldPrettyNames', "Flows")
QCoreApplication.translate('FieldPrettyNames', "Friction factors")
QCoreApplication.translate('FieldPrettyNames', "Full demands")
QCoreApplication.translate('FieldPrettyNames', "Head Curves")
QCoreApplication.translate('FieldPrettyNames', "Head Patterns")
QCoreApplication.translate('FieldPrettyNames', "HeadLoss Curves")
QCoreApplication.translate('FieldPrettyNames', "HeadLosses")
QCoreApplication.translate('FieldPrettyNames', "Heads")
QCoreApplication.translate('FieldPrettyNames', "Initial Levels")
QCoreApplication.translate('FieldPrettyNames', "Initial Statuses")
QCoreApplication.translate('FieldPrettyNames', "Installation Dates")
QCoreApplication.translate('FieldPrettyNames', "Leak Areas")
QCoreApplication.translate('FieldPrettyNames', "Leak Expansion Rates")
QCoreApplication.translate('FieldPrettyNames', "Leakage Flows")
QCoreApplication.translate('FieldPrettyNames', "Lengths")
QCoreApplication.translate('FieldPrettyNames', "Link Types")
QCoreApplication.translate('FieldPrettyNames', "Loss Coefficients")
QCoreApplication.translate('FieldPrettyNames', "Materials")
QCoreApplication.translate('FieldPrettyNames', "Maximum Levels")
QCoreApplication.translate('FieldPrettyNames', "Meter Types")
QCoreApplication.translate('FieldPrettyNames', "Minimum Pressures")
QCoreApplication.translate('FieldPrettyNames', "Minimum Volumes")
QCoreApplication.translate('FieldPrettyNames', "Mixing Fractions")
QCoreApplication.translate('FieldPrettyNames', "Mixing Models")
QCoreApplication.translate('FieldPrettyNames', "Node Types")
QCoreApplication.translate('FieldPrettyNames', "Overflow Conditions")
QCoreApplication.translate('FieldPrettyNames', "Pattern Demands")
QCoreApplication.translate('FieldPrettyNames', "Pattern Types")
QCoreApplication.translate('FieldPrettyNames', "Pressure Exponents")
QCoreApplication.translate('FieldPrettyNames', "Pressures")
QCoreApplication.translate('FieldPrettyNames', "Price Patterns")
QCoreApplication.translate('FieldPrettyNames', "Pump Curves")
QCoreApplication.translate('FieldPrettyNames', "Quality Patterns")
QCoreApplication.translate('FieldPrettyNames', "Reaction Rates")
QCoreApplication.translate('FieldPrettyNames', "Required Pressures")
QCoreApplication.translate('FieldPrettyNames', "Roughness Coeffs")
QCoreApplication.translate('FieldPrettyNames', "Settings")
QCoreApplication.translate('FieldPrettyNames', "Source Patterns")
QCoreApplication.translate('FieldPrettyNames', "Source Types")
QCoreApplication.translate('FieldPrettyNames', "Speed Patterns")
QCoreApplication.translate('FieldPrettyNames', "Speeds")
QCoreApplication.translate('FieldPrettyNames', "Statuses")
QCoreApplication.translate('FieldPrettyNames', "Tags")
QCoreApplication.translate('FieldPrettyNames', "Tank Volumes")
QCoreApplication.translate('FieldPrettyNames', "Total Heads")
QCoreApplication.translate('FieldPrettyNames', "Types")
QCoreApplication.translate('FieldPrettyNames', "Unit HeadLosses")
QCoreApplication.translate('FieldPrettyNames', "Valve Types")
QCoreApplication.translate('FieldPrettyNames', "Velocities")
QCoreApplication.translate('FieldPrettyNames', "Volume Curves")
QCoreApplication.translate('FieldPrettyNames', "Volumes")
QCoreApplication.translate('FieldPrettyNames', "Wall Coefficients")

# Unit full names (getUnitFullName) — context 'UnitFullNames'
QCoreApplication.translate('UnitFullNames', "Meters")
QCoreApplication.translate('UnitFullNames', "Feet")
QCoreApplication.translate('UnitFullNames', "Millimeters")
QCoreApplication.translate('UnitFullNames', "Inches")
QCoreApplication.translate('UnitFullNames', "Millifeet")
QCoreApplication.translate('UnitFullNames', "sq mm per 100 m")
QCoreApplication.translate('UnitFullNames', "sq mm per unit press")
QCoreApplication.translate('UnitFullNames', "liters/sec")
QCoreApplication.translate('UnitFullNames', "liters/min")
QCoreApplication.translate('UnitFullNames', "megaliters/day")
QCoreApplication.translate('UnitFullNames', "cubic metres/hr")
QCoreApplication.translate('UnitFullNames', "cubic metres/day")
QCoreApplication.translate('UnitFullNames', "Cubic feet/sec")
QCoreApplication.translate('UnitFullNames', "Gallons/min")
QCoreApplication.translate('UnitFullNames', "Million gal/day")
QCoreApplication.translate('UnitFullNames', "Imperial MGD")
QCoreApplication.translate('UnitFullNames', "Acre-feet/day")
QCoreApplication.translate('UnitFullNames', "cubic meters/sec")
QCoreApplication.translate('UnitFullNames', "Meters water column")
QCoreApplication.translate('UnitFullNames', "KiloPascals")
QCoreApplication.translate('UnitFullNames', "bars")
QCoreApplication.translate('UnitFullNames', "Feet water column")
QCoreApplication.translate('UnitFullNames', "Pounds/ sq inch")
QCoreApplication.translate('UnitFullNames', "Meters/second")
QCoreApplication.translate('UnitFullNames', "feet/second")
QCoreApplication.translate('UnitFullNames', "Meters per 1000 m")
QCoreApplication.translate('UnitFullNames', "Feet per 1000 ft")
QCoreApplication.translate('UnitFullNames', "Flow/sqr(Pressure)")
QCoreApplication.translate('UnitFullNames', "seconds/meters(1/3)")
QCoreApplication.translate('UnitFullNames', "Kilowatts")
QCoreApplication.translate('UnitFullNames', "Horse Power")
QCoreApplication.translate('UnitFullNames', "Kilowatt - hours")
QCoreApplication.translate('UnitFullNames', "Miligrams")
QCoreApplication.translate('UnitFullNames', "Micrograms")
QCoreApplication.translate('UnitFullNames', "Mass/Liter")
QCoreApplication.translate('UnitFullNames', "mass/Liter")
QCoreApplication.translate('UnitFullNames', "Mass/L/day")
QCoreApplication.translate('UnitFullNames', "mass/L/day")
QCoreApplication.translate('UnitFullNames', "mass/L")
QCoreApplication.translate('UnitFullNames', "Mass/minute")
QCoreApplication.translate('UnitFullNames', "mass/minute")
QCoreApplication.translate('UnitFullNames', "Percent")
QCoreApplication.translate('UnitFullNames', "Hours")
QCoreApplication.translate('UnitFullNames', "Years")
QCoreApplication.translate('UnitFullNames', "Per day")
QCoreApplication.translate('UnitFullNames', "Unitless")
QCoreApplication.translate('UnitFullNames', "Cubic feet")
QCoreApplication.translate('UnitFullNames', "Cubic meters")
QCoreApplication.translate('UnitFullNames', "USDollars")
QCoreApplication.translate('UnitFullNames', "Euros")
QCoreApplication.translate('UnitFullNames', "GBPounds")
QCoreApplication.translate('UnitFullNames', "Yenes")
QCoreApplication.translate('UnitFullNames', "Yuanes")
QCoreApplication.translate('UnitFullNames', "Currency /kWh")
QCoreApplication.translate('UnitFullNames', "Currency /Max kW")
QCoreApplication.translate('UnitFullNames', "Time as Text")
QCoreApplication.translate('UnitFullNames', "Year as Text")

# Layer names shown in QGIS legend (Inputs group)
QCoreApplication.translate('InputLayerNames', "Pipes")
QCoreApplication.translate('InputLayerNames', "Junctions")
QCoreApplication.translate('InputLayerNames', "Multiple Demands")
QCoreApplication.translate('InputLayerNames', "Reservoirs")
QCoreApplication.translate('InputLayerNames', "Tanks")
QCoreApplication.translate('InputLayerNames', "Pumps")
QCoreApplication.translate('InputLayerNames', "Valves")
QCoreApplication.translate('InputLayerNames', "Sources")
QCoreApplication.translate('InputLayerNames', "Service Connections")
QCoreApplication.translate('InputLayerNames', "Isolation Valves")
QCoreApplication.translate('InputLayerNames', "Meters")
# Demand Builder auxiliary theme types, looked up by key in the layer manager
QCoreApplication.translate('AuxiliaryTypeNames', "Consumption Points")
QCoreApplication.translate('AuxiliaryTypeNames', "Demand Links")
QCoreApplication.translate('AuxiliaryTypeNames', "Demand Sectors")
# Layer names shown in QGIS legend (Queries group)
QCoreApplication.translate('InputLayerNames', "Connect_Links")
QCoreApplication.translate('InputLayerNames', "HydSec_Links")
QCoreApplication.translate('InputLayerNames', "HydSec_Nodes")
QCoreApplication.translate('InputLayerNames', "HydSec_Isolated Demands")
QCoreApplication.translate('InputLayerNames', "DemSec_Links")
QCoreApplication.translate('InputLayerNames', "DemSec_Nodes")
QCoreApplication.translate('InputLayerNames', "IsolSeg_Links")
QCoreApplication.translate('InputLayerNames', "IsolSeg_Nodes")
QCoreApplication.translate('InputLayerNames', "IsolSeg_Isolated Demands")
QCoreApplication.translate('InputLayerNames', "Tree_Links")
QCoreApplication.translate('InputLayerNames', "Tree_Nodes")
QCoreApplication.translate('InputLayerNames', "DemBuild_Demand Links")
QCoreApplication.translate('InputLayerNames', "DemBuild_Consumption Points")
QCoreApplication.translate('InputLayerNames', "DemBuild_Isolated Demands Connections")
QCoreApplication.translate('InputLayerNames', "DemBuild_Sectors")
QCoreApplication.translate('InputLayerNames', "%1 I")
# Layer names shown in QGIS legend (Thematic Maps group).
# Only the maps the dialog actually exposes: tempElementsHide() hides the rest.
QCoreApplication.translate('InputLayerNames', "Pipe Diameters")
QCoreApplication.translate('InputLayerNames', "Pipe Lengths")
QCoreApplication.translate('InputLayerNames', "Pipe Materials")
QCoreApplication.translate('InputLayerNames', "Pipe Roughnesses")
QCoreApplication.translate('InputLayerNames', "Pipe Installation Year")
QCoreApplication.translate('InputLayerNames', "Pipe Ages")
QCoreApplication.translate('InputLayerNames', "Junction Base Demands")
QCoreApplication.translate('InputLayerNames', "Junction Elevations")

# Histogram hover tooltips (renderers call widget.tr with these contexts)
QCoreApplication.translate('StatisticsHistogramWidget', "No data")
QCoreApplication.translate('StatisticsHistogramWidget', "Count")
QCoreApplication.translate('StatisticsHistogramWidget', "Sum")
QCoreApplication.translate('StatisticsHistogramWidget', "Avg")
QCoreApplication.translate('StatisticsHistogramWidget', "Total")
QCoreApplication.translate('ResultsDistributionWidget', "Count")
QCoreApplication.translate('ResultsDistributionWidget', "Cumulative")
QCoreApplication.translate('ResultsDistributionWidget', "Value")

# Results distribution histogram (mixin uses QGISRedResultsDock context)
QCoreApplication.translate('QGISRedResultsDock', "Absolute")
QCoreApplication.translate('QGISRedResultsDock', "Relative")
QCoreApplication.translate('QGISRedResultsDock', "Count")
QCoreApplication.translate('QGISRedResultsDock', "Freq")
QCoreApplication.translate('QGISRedResultsDock', "Cumul")
QCoreApplication.translate('QGISRedResultsDock', "%1 frequency%2")
QCoreApplication.translate('QGISRedResultsDock', "Closed")
QCoreApplication.translate('QGISRedResultsDock', "Open")
QCoreApplication.translate('QGISRedResultsDock', "Active")
QCoreApplication.translate('QGISRedResultsDock', "Expand histogram to a floating window")
QCoreApplication.translate('QGISRedResultsDock', "Collapse histogram back to the panel")
QCoreApplication.translate('QGISRedResultsDock', "Histogram")
QCoreApplication.translate('QGISRedResultsDock', "Show Node Evolution")
QCoreApplication.translate('QGISRedResultsDock', "Show Link Evolution")
QCoreApplication.translate('QGISRedResultsDock', "Overflow")
QCoreApplication.translate('QGISRedResultsDock', "Show stored volume instead")
QCoreApplication.translate('QGISRedResultsDock', "Show overflow flow instead")
QCoreApplication.translate('QGISRedResultsDock', "Expand chart to a floating window")
QCoreApplication.translate('QGISRedResultsDock', "Collapse chart back to the panel")
QCoreApplication.translate('QGISRedResultsDock', "Evolution")

# Statistics histogram UI
QCoreApplication.translate('QGISRedStatisticsDock', "Mouse wheel: zoom · Drag: pan · Double-click: reset view")
QCoreApplication.translate('QGISRedStatisticsDock', "by")
QCoreApplication.translate('QGISRedStatisticsDock', "Count")

# Valve type long names and abbreviations (see tools/utils/qgisred_valve_types.py —
# VALVE_TYPE_LONG_NAMES keys mirrored here so pylupdate5 can see them; the module
# itself only ever calls translate() with a variable, which pylupdate can't extract).
QCoreApplication.translate('ValveTypeNames', "Pressure Reducing")
QCoreApplication.translate('ValveTypeNames', "Pressure Sustaining")
QCoreApplication.translate('ValveTypeNames', "Pressure Breaker")
QCoreApplication.translate('ValveTypeNames', "Flow Control")
QCoreApplication.translate('ValveTypeNames', "Throttle Control")
QCoreApplication.translate('ValveTypeNames', "General Purpose")
QCoreApplication.translate('ValveTypeNames', "Check")
QCoreApplication.translate('ValveTypeAbbreviations', "PRV")
QCoreApplication.translate('ValveTypeAbbreviations', "PSV")
QCoreApplication.translate('ValveTypeAbbreviations', "PBV")
QCoreApplication.translate('ValveTypeAbbreviations', "FCV")
QCoreApplication.translate('ValveTypeAbbreviations', "TCV")
QCoreApplication.translate('ValveTypeAbbreviations', "GPV")
QCoreApplication.translate('ValveTypeAbbreviations', "CV")
