# -*- coding: utf-8 -*-
# Translatable strings that pylupdate5 cannot extract automatically.
# Calling QCoreApplication.translate() directly with literal strings
# so pylupdate5 picks them up when generating/updating .ts files.
from qgis.PyQt.QtCore import QCoreApplication

# Common fields
QCoreApplication.translate('FieldPrettyNames', "Identifier")
QCoreApplication.translate('FieldPrettyNames', "Tag")
QCoreApplication.translate('FieldPrettyNames', "Description")
QCoreApplication.translate('FieldPrettyNames', "Age")
QCoreApplication.translate('FieldPrettyNames', "Installation Date")
QCoreApplication.translate('FieldPrettyNames', "Initial Status")
QCoreApplication.translate('FieldPrettyNames', "Type")
QCoreApplication.translate('FieldPrettyNames', "Status")
QCoreApplication.translate('FieldPrettyNames', "IsActive")

# Pipes
QCoreApplication.translate('FieldPrettyNames', "Length")
QCoreApplication.translate('FieldPrettyNames', "Diameter")
QCoreApplication.translate('FieldPrettyNames', "Roughness Coeff")
QCoreApplication.translate('FieldPrettyNames', "Loss Coefficient")
QCoreApplication.translate('FieldPrettyNames', "Material")
QCoreApplication.translate('FieldPrettyNames', "Leak Area")
QCoreApplication.translate('FieldPrettyNames', "Leak Expansion Rate")
QCoreApplication.translate('FieldPrettyNames', "Bulk Coefficient")
QCoreApplication.translate('FieldPrettyNames', "Wall Coefficient")

# Junctions
QCoreApplication.translate('FieldPrettyNames', "Elevation")
QCoreApplication.translate('FieldPrettyNames', "Base Demand")
QCoreApplication.translate('FieldPrettyNames', "Pattern Demand")
QCoreApplication.translate('FieldPrettyNames', "Emitter Coefficient")
QCoreApplication.translate('FieldPrettyNames', "Initial Quality")

# Multiple Demands
QCoreApplication.translate('FieldPrettyNames', "Base Demand")

# Tanks
QCoreApplication.translate('FieldPrettyNames', "Initial Level")
QCoreApplication.translate('FieldPrettyNames', "MinimumLevel")
QCoreApplication.translate('FieldPrettyNames', "Maximum Level")
QCoreApplication.translate('FieldPrettyNames', "Volume")
QCoreApplication.translate('FieldPrettyNames', "Volume Curve")
QCoreApplication.translate('TimeSeriesGlobals', "Total Water Supply")
QCoreApplication.translate('TimeSeriesGlobals', "Total Water Demand")
QCoreApplication.translate('TimeSeriesGlobals', "Total Stored Volume")
QCoreApplication.translate('TimeSeriesGlobals', "Total Tank Spill Flow")
QCoreApplication.translate('TimeSeriesGlobals', "Average Node Pressure")
QCoreApplication.translate('TimeSeriesGlobals', "System")
QCoreApplication.translate('TimeSeriesGlobals', "Supply")
QCoreApplication.translate('TimeSeriesGlobals', "Demand")
QCoreApplication.translate('TimeSeriesGlobals', "Storage")
QCoreApplication.translate('TimeSeriesGlobals', "Spill")
QCoreApplication.translate('TimeSeriesGlobals', "Pressure")
QCoreApplication.translate('FieldPrettyNames', "Overflow Condition")
QCoreApplication.translate('FieldPrettyNames', "Mixing Model")
QCoreApplication.translate('FieldPrettyNames', "Mixing Fraction")

# Reservoirs
QCoreApplication.translate('FieldPrettyNames', "Total Head")
QCoreApplication.translate('FieldPrettyNames', "Head Pattern")

# Valves
QCoreApplication.translate('FieldPrettyNames', "Setting")
QCoreApplication.translate('FieldPrettyNames', "HeadLoss Curve")

# Pumps
QCoreApplication.translate('FieldPrettyNames', "Head Curve")
QCoreApplication.translate('FieldPrettyNames', "Power")
QCoreApplication.translate('FieldPrettyNames', "Speed")
QCoreApplication.translate('FieldPrettyNames', "Speed Pattern")
QCoreApplication.translate('FieldPrettyNames', "Efficiency Curve")
QCoreApplication.translate('FieldPrettyNames', "Energy Price")
QCoreApplication.translate('FieldPrettyNames', "Price Pattern")

# Curves
QCoreApplication.translate('FieldPrettyNames', "Value X axis")
QCoreApplication.translate('FieldPrettyNames', "Value Y axis")

# Sources
QCoreApplication.translate('FieldPrettyNames', "Source Quality")
QCoreApplication.translate('FieldPrettyNames', "Source Pattern")

# Service Connections
QCoreApplication.translate('FieldPrettyNames', "Reliability")

# Isolation Valves
QCoreApplication.translate('FieldPrettyNames', "Available")

# Options
QCoreApplication.translate('FieldPrettyNames', "Specific Gravity")
QCoreApplication.translate('FieldPrettyNames', "Viscosity")
QCoreApplication.translate('FieldPrettyNames', "Demand Multiplier")
QCoreApplication.translate('FieldPrettyNames', "Emitter Exponent")
QCoreApplication.translate('FieldPrettyNames', "Minimum Pressure")
QCoreApplication.translate('FieldPrettyNames', "Required Pressure")
QCoreApplication.translate('FieldPrettyNames', "Pressure Exponent")
QCoreApplication.translate('FieldPrettyNames', "Diffusivity")
QCoreApplication.translate('FieldPrettyNames', "Global Bulk")
QCoreApplication.translate('FieldPrettyNames', "Global Wall")
QCoreApplication.translate('FieldPrettyNames', "Limiting Potential")
QCoreApplication.translate('FieldPrettyNames', "Global Efficiency")
QCoreApplication.translate('FieldPrettyNames', "Global Price")
QCoreApplication.translate('FieldPrettyNames', "Demand Charge")

# Result nodes
QCoreApplication.translate('FieldPrettyNames', "Pressure")
QCoreApplication.translate('FieldPrettyNames', "Head")
QCoreApplication.translate('FieldPrettyNames', "Demand")
QCoreApplication.translate('FieldPrettyNames', "Full demand")
QCoreApplication.translate('FieldPrettyNames', "Demand Deficit")
QCoreApplication.translate('FieldPrettyNames', "Leakage Flow")
QCoreApplication.translate('FieldPrettyNames', "Emitter Flow")

# Result links
QCoreApplication.translate('FieldPrettyNames', "Flow")
QCoreApplication.translate('FieldPrettyNames', "Velocity")
QCoreApplication.translate('FieldPrettyNames', "HeadLoss")
QCoreApplication.translate('FieldPrettyNames', "Unit HeadLoss")
QCoreApplication.translate('FieldPrettyNames', "Friction factor")
QCoreApplication.translate('FieldPrettyNames', "Energy")
QCoreApplication.translate('FieldPrettyNames', "Reaction Rate")

# Result nodes and links
QCoreApplication.translate('FieldPrettyNames', "Element Type")
QCoreApplication.translate('FieldPrettyNames', "Simulation Time")

# Quality results (dynamic — also translated via getQualityDisplayName)
QCoreApplication.translate('FieldPrettyNames', "Chemical")
QCoreApplication.translate('FieldPrettyNames', "Trace")

# Unit full names (getUnitFullName) — context 'UnitFullNames'
QCoreApplication.translate('UnitFullNames', "Meters")
QCoreApplication.translate('UnitFullNames', "Feet")
QCoreApplication.translate('UnitFullNames', "Millimeters")
QCoreApplication.translate('UnitFullNames', "Inches")
QCoreApplication.translate('UnitFullNames', "Millifeet")
QCoreApplication.translate('UnitFullNames', "sq mm per 100 m")
QCoreApplication.translate('UnitFullNames', "sq mm per unit press")
QCoreApplication.translate('UnitFullNames', "liters/sec")
QCoreApplication.translate('UnitFullNames', "liters/min")
QCoreApplication.translate('UnitFullNames', "megaliters/day")
QCoreApplication.translate('UnitFullNames', "cubic metres/hr")
QCoreApplication.translate('UnitFullNames', "cubic metres/day")
QCoreApplication.translate('UnitFullNames', "Cubic feet/sec")
QCoreApplication.translate('UnitFullNames', "Gallons/min")
QCoreApplication.translate('UnitFullNames', "Million gal/day")
QCoreApplication.translate('UnitFullNames', "Imperial MGD")
QCoreApplication.translate('UnitFullNames', "Acre-feet/day")
QCoreApplication.translate('UnitFullNames', "cubic meters/sec")
QCoreApplication.translate('UnitFullNames', "Meters water column")
QCoreApplication.translate('UnitFullNames', "KiloPascals")
QCoreApplication.translate('UnitFullNames', "bars")
QCoreApplication.translate('UnitFullNames', "Feet water column")
QCoreApplication.translate('UnitFullNames', "Pounds/ sq inch")
QCoreApplication.translate('UnitFullNames', "Meters/second")
QCoreApplication.translate('UnitFullNames', "feet/second")
QCoreApplication.translate('UnitFullNames', "Meters per 1000 m")
QCoreApplication.translate('UnitFullNames', "Feet per 1000 ft")
QCoreApplication.translate('UnitFullNames', "Flow/sqr(Pressure)")
QCoreApplication.translate('UnitFullNames', "seconds/meters(1/3)")
QCoreApplication.translate('UnitFullNames', "Kilowatts")
QCoreApplication.translate('UnitFullNames', "Horse Power")
QCoreApplication.translate('UnitFullNames', "Kilowatt - hours")
QCoreApplication.translate('UnitFullNames', "Miligrams")
QCoreApplication.translate('UnitFullNames', "Micrograms")
QCoreApplication.translate('UnitFullNames', "Mass/Liter")
QCoreApplication.translate('UnitFullNames', "mass/Liter")
QCoreApplication.translate('UnitFullNames', "Mass/L/day")
QCoreApplication.translate('UnitFullNames', "mass/L/day")
QCoreApplication.translate('UnitFullNames', "mass/L")
QCoreApplication.translate('UnitFullNames', "Mass/minute")
QCoreApplication.translate('UnitFullNames', "mass/minute")
QCoreApplication.translate('UnitFullNames', "Percent")
QCoreApplication.translate('UnitFullNames', "Hours")
QCoreApplication.translate('UnitFullNames', "Years")
QCoreApplication.translate('UnitFullNames', "Per day")
QCoreApplication.translate('UnitFullNames', "Unitless")
QCoreApplication.translate('UnitFullNames', "Cubic feet")
QCoreApplication.translate('UnitFullNames', "Cubic meters")
QCoreApplication.translate('UnitFullNames', "USDollars")
QCoreApplication.translate('UnitFullNames', "Euros")
QCoreApplication.translate('UnitFullNames', "GBPounds")
QCoreApplication.translate('UnitFullNames', "Yenes")
QCoreApplication.translate('UnitFullNames', "Yuanes")
QCoreApplication.translate('UnitFullNames', "Currency /kWh")
QCoreApplication.translate('UnitFullNames', "Currency /Max kW")
QCoreApplication.translate('UnitFullNames', "Time as Text")
QCoreApplication.translate('UnitFullNames', "Year as Text")

# Layer names shown in QGIS legend (Inputs group)
QCoreApplication.translate('InputLayerNames', "Pipes")
QCoreApplication.translate('InputLayerNames', "Junctions")
QCoreApplication.translate('InputLayerNames', "Multiple Demands")
QCoreApplication.translate('InputLayerNames', "Reservoirs")
QCoreApplication.translate('InputLayerNames', "Tanks")
QCoreApplication.translate('InputLayerNames', "Pumps")
QCoreApplication.translate('InputLayerNames', "Valves")
QCoreApplication.translate('InputLayerNames', "Sources")
QCoreApplication.translate('InputLayerNames', "Service Connections")
QCoreApplication.translate('InputLayerNames', "Isolation Valves")
QCoreApplication.translate('InputLayerNames', "Meters")
QCoreApplication.translate('InputLayerNames', "Hydrants")
QCoreApplication.translate('InputLayerNames', "Washout Valves")
QCoreApplication.translate('InputLayerNames', "Air Release Valves")
# Layer names shown in QGIS legend (Queries group)
QCoreApplication.translate('InputLayerNames', "Connect_Links")
QCoreApplication.translate('InputLayerNames', "HydSec_Links")
QCoreApplication.translate('InputLayerNames', "HydSec_Nodes")
QCoreApplication.translate('InputLayerNames', "HydSec_Isolated Demands")
QCoreApplication.translate('InputLayerNames', "DemSec_Links")
QCoreApplication.translate('InputLayerNames', "DemSec_Nodes")
QCoreApplication.translate('InputLayerNames', "IsolSeg_Links")
QCoreApplication.translate('InputLayerNames', "IsolSeg_Nodes")
QCoreApplication.translate('InputLayerNames', "IsolSeg_Isolated Demands")
QCoreApplication.translate('InputLayerNames', "Tree_Links")
QCoreApplication.translate('InputLayerNames', "Tree_Nodes")
QCoreApplication.translate('InputLayerNames', "DemBuil_Demand Links")
QCoreApplication.translate('InputLayerNames', "DemBuil_Consumption Points")
QCoreApplication.translate('InputLayerNames', "%1 I")
# Layer names shown in QGIS legend (Thematic Maps group)
QCoreApplication.translate('InputLayerNames', "Pipe Diameters")
QCoreApplication.translate('InputLayerNames', "Pipe Lengths")
QCoreApplication.translate('InputLayerNames', "Pipe Materials")
